# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('portfolio_app', '0003_auto_20191117_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('endpoint_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_on', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='option_owned', to='portfolio_app.Option')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='number_owned', to='login_app.User')),
            ],
        ),
    ]
