# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_dailysummary_quantityoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginrequired',
            name='user',
        ),
        migrations.RenameField(
            model_name='dailysummary',
            old_name='on',
            new_name='summary_on',
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='endpoint',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='endpoint_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='MarginRequired',
        ),
    ]
