# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20191120_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityoptions',
            old_name='count',
            new_name='option_count',
        ),
        migrations.AlterField(
            model_name='quantityoptions',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='option_owned', to='portfolio_app.Option'),
        ),
        migrations.AlterField(
            model_name='quantityoptions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='number_owned', to='login_app.User'),
        ),
    ]
