# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_auto_20191120_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='users_who_own',
        ),
    ]
